export { default as App } from "./app";
export { default as Profile } from "./profile";
export { default as ConnectToWallet } from "./connectToWallet";
export { default as Balances } from "./balances";
export { default as Payments } from "./payments";
export { default as About } from "./about";
export { default as SplitterBalances } from "./splitterBalances";
export { default as BalanceSheet } from "./balanceSheet";
export { default as InteractWithSplitter } from "./interactWithSplitter";
